### ISSUE TITLE
[System] Peripherals can automatically go to sleep when Inactive

### ISSUE THREAD

**Issue by feren** [feren-OS/feren-OS-Bug-Repoting#3]
For Non-portable PC Users of feren OS, the USB-connected mice and keyboards will go to sleep when inactive for a certain amount of time all the time with the only way of waking them up being clicking for the mouse and sacrificing a key press for the keyboards...

Doesn't affect Wired Mice

**Comment by swoopa** [comment]
Experiencing mouse and keyboard sleeping on Intel Skull Canyon NUC i7-6770HQ CPU@2.6GHzx4,
Tried reinstall systemd and libdbus-1-3 (tried libdbus) unable to locate package?

**Comment by feren** [comment]
@swoopa Ok, try it without the "missing" package... (BUT MAKE SURE TO REFRESH REPOSITORIES IN CASE YOU THAT'S WHY IT'S MISSING)

**Comment by swoopa** [comment]
@feren it was the libdbus-1-3 I installed, I was trying to install (libdbus) "only" that's why I got the error, anyway I installed libdbus-1-3, then ran sudo install --reinstall libdbus-1-3 systemd and so far everything is working well I'm happy to report.I need to reformat my drive so I will do another fresh install and make sure I didn't fluke it..lol, thanks for the help!!

**Comment by feren** [comment]
YES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by swoopa** [comment]
@feren I did a fresh install, I have run the command sudo install --reinstall libdbus-1-3 systemd and this time around it has not worked, differences with installs, first install to WD500GB black external USB installed to the whole hard drive primary partition, this install to 30GB Logical Partition booted from grub controlled by ubuntu 16.04 does this set up affect this issue?

**Comment by swoopa** [comment]
@feren Sorry I may have messaged a bit early it's now running ok, still a bit sticky at login screen, is ok once logged in, took a bit longer on this install than previous don't know why? run the command several times and also tried reinstall with synaptic.

**Comment by feren** [comment]
Fixed in feren OS 2017.0 Pre-BETA and onwards

**Comment by feren** [comment]
@swoopa Odd, no matter how many times we try it, it isn't fixed for Sudo Reboot... :/
